language: minimal

stages:
    - build
    - test


linuxCompilation:        
    - install:
        - export BIN=${HOME}/bin
        - mkdir ${BIN} && cd ${BIN}
        - g++ -v

    - script:
        - g++ compile.cpp -o out
        - echo ${BIN}

jobs:
    include:
        - stage: install
          name: "linuxCompilation"
          install: skip
          script:
            - g++ compile.cpp -o out
